import Footer from "./components/Footer/Footer";
import Navbar from "./components/Header/Navbar";
import "./globals.css";
import LoadingPage from "./loading";
import NotFoundPage from "./not-found";

export const metadata = {
  title: "TaskMama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-roboto`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <LoadingPage/>
        <NotFoundPage/>
      </body>
    </html>
  );
}
