import Navbar from "./components/Header/Navbar";
import "./globals.css";

export const metadata = {
  title: "TaskMama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-roboto`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
